### ISSUE TITLE
no connection to my usb2serial

### ISSUE THREAD

**Issue by sander816** [rvleij/p1monitor#4] opened 2021-09-17 11:15 UTC
i started this docker with thuis command:
```
docker run -d -p 83:80 -p 10721:10721 -p 40721:40721 --name="p1mon" \
-h p1mon --cap-add=SYS_NICE \
--tmpfs /tmp --tmpfs /run -v /mnt/usb/p1mon/ramdisk:/p1mon/mnt/ramdisk:rw \
-v /mnt/usb/p1mon/data:/p1mon/data:rw -v /mnt/usb/p1mon/usbdisk:/p1mon/mnt/usb:rw \
-v /etc/localtime:/etc/localtime:ro \
--device=/dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0 \
--restart=unless-stopped \
rvleij/p1monitor
```
but, i cannot get a connection to my serial to p1 adapter.
in HA this works fine: /dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0

**Comment by rvleij** [comment] 2021-09-17 13:05
Hmm, what if you put it in quotes or double quotes? What's the error actually? For me this works, though I don't use that mapping I just use 

`--device=/dev/ttyUSB0 \`

on that line. Have you tried mapping with other paths, like ttyUSB0 or however, because the "by-id" should also have another mapping. Lastly: the device is not in use by something else, right?

**Comment by sander816** [comment] 2021-09-17 13:50
no error when starting, theres just no connection to the serial device

**Comment by sander816** [comment] 2021-09-17 13:50
well, its is by HA, guess illtry to remove the hassio integration, reboot. And try ttyusb

**Comment by hemant5400z** [comment] 2021-09-27 13:55
Hi Sander816,

If you are connected with HA, your device is already claimed, you cannot claim it for a second time as the sreial connection is already in use.

Cheers,

Hemant

**Comment by mvank** [comment] 2021-09-27 14:48
For this reason I have 2 p1 cables connected to my nuc running ha and p1monitor in Docker. P1 cable is connected with a splitter to my smart meter.

**Comment by hemant5400z** [comment] 2021-09-27 14:58
No need for 2 serial adapaters you can achive 10+ conection with Ser2net.

Hemant

**Comment by mvank** [comment] 2021-11-13 08:28
Hi Robin @rvleij,

Is it possible to have socat by default in the image?
I am using now ser2net with socat which is working fine. It would be nice to have the option from the image to directly use socat.

Michel

**Comment by rvleij** [comment] 2021-11-14 13:24
Absolutely. Please let me know what you’d normally do to install socat. I’m also going to read about it to understand how including it in the image helps / works. So let me know how installation works (like apt get blah) and if there’s any version dependence

**Comment by rvleij** [comment] 2021-11-14 13:25
Reopened to include util in image.

**Comment by mvank** [comment] 2021-11-14 13:39
Hi @rvleij,

I used this article:
https://community.openhab.org/t/share-z-wave-dongle-over-ip-usb-over-ip-using-ser2net-socat-guide/34895 starting from: **_USB device client (OpenHAB running on a virtual linux machine IP=172.16.11.4 replace with you IP)_**

I have added a file for socat settings:
_-e /socat.conf:/etc/default/socat.conf_

**socat.conf file:**
_OPTIONS="pty,link=/dev/ttyUSB0,raw,user=p1mon,group=dialout,mode=777 tcp:192.168.1.15:5000"_

SER2NET is configured with 192.168.1.15:5000

**configured container:**
> apt install socat
> git clone https://github.com/asaif/socat-init.git
> cp socat-init/socat /etc/init.d/ 
> chmod +x /etc/init.d/socat 
> service socat restart

I have creates a script to check if socat exists and is running.
Also I added in /etc/init.d/crontab to check every minute if socat is still running

Michel

**Comment by rvleij** [comment] 2021-11-15 08:13
OK, I'll get to work on this. I'll have to travel for work, so I'll look at this towards the weekend. Proabably I can make a feature branch, release it with a tag and then you test it?
I understand after reading a bit that this is more or less the client that connects to a remote dongle. So what I'll have to figure out is how to get that config via Docker environment vars, because not everyone is running their ser2net on 192.168.1.15. :)

In fact, wouldn't it be more logical to just run https://hub.docker.com/r/alpine/socat and then use that USB device for P1Monitor compared to mixing two "tasks" into one container?

but anway, if I can figure out how to configure socat (also looking at that other container) then for me it's allright to include the "client" for serial over network, it makes sense I think.

**Comment by mvank** [comment] 2021-11-16 12:28
`not everyone is running their ser2net on 192.168.1.15. :)` 

I use as configuration file now to map this file with docker volume, which was a solution for me for now.

```
-e /socat.conf:/etc/default/socat.conf

socat.conf file:
OPTIONS="pty,link=/dev/ttyUSB0,raw,user=p1mon,group=dialout,mode=777 tcp:192.168.1.15:5000"
```

**Comment by hemant5400z** [comment] 2021-11-16 14:29
@rvleij @mvank ,

The problem can be solved in 2 ways.

Options 1: provide socat in the docker and configure like I did, but users will need to have ip and port setup when starting socat before start_all.sh is kicked. I my case i created a script to for socat and put this as one of the first lines in start_all.sh to amke sure it runs otherwise you will get erros until com-port is available, also a checked script is running in the background to monitor socat and restarts if required ( tcp packet drop will crash socat).
or first to apt-get update -> apk-get install socat and call socat and start_all.sh from start.sh.

Option 2: have and addtional option in P1monitor to select com-port or tcp port similar to domoticz/home assistant, the user can than setup his personal setup tcp or serial rather then worrying about socat and additional software required. This way you are more flexible and no addtional software install is required.

Cheers,
Hemant

**Comment by rvleij** [comment] 2021-11-24 09:27
Hi, sorry for getting back a bit late, but what do you mean with option 2?

Option 1 I get: I'd include socat with the instructions you sent me and provide an option to map a config file. If that file is not mapped when starting the container, then by default I'd include an empty config file that wouldn't "do anything". I'd go for the second option, to include the install in the docker script using apt and then start it from start.sh before start_all.sh.

But what do you mean with option 2, like the "similar to home-assistant? Wouldn't that mean changes to the actual p1monitor?

Let me know. I think I make a new tag based on a feature branch in this repo, so you can test the image before I make it the "default". Option 1 that is.

**Comment by hemant5400z** [comment] 2021-11-24 10:31
Hi,

In Domoticz you can choose between 2 types. 
first 1 is serial connection (which you already have in the screen)
second: tcp connection (this is a pull down in the interface) see below.

The user can then select (normal USB or TCP)

![image](https://user-images.githubusercontent.com/16900394/143221800-42c86f5e-b8dc-4844-8633-e8e7fe6205d6.png)

**Comment by rvleij** [comment] 2021-11-24 12:54
Ok, I don't think I can control that, since it's part of p1mon (I'm not the author of P1Mon, please make feature request there).
I now have a an image (amd64 only for now) tagged "testing" which is including socat, but it's not running yet because I also upgraded to the new debian and I have to fix some python dependencies. I'll continue later and report here when you can switch tags to test 1.4.1 with socat installed in the image.

**Comment by mvank** [comment] 2021-11-26 14:42
I used the tested version, as you mentioned socat is not running yet, not know as a service yet...

**Comment by rvleij** [comment] 2021-11-26 23:15
OK, try again. The state where I got now is:

1. Reverted my Debian upgrade to Bullseye, I'm too tired to fix all the issues so let's wait until the actual p1monitor moves to the new Debian. :) 
2. I've hardcoded the whole socat thing, using forever and interval=10 to make it more stable at startup. However, if I read the manual correctly it'll fail if you connect and THEN disconnect on the other side, so I have to figure that out. I've hardcoded your .15, so you can test, I'll have to figure as well how to pass config parameters haha.

So please test if everything works with testing tag. Then I'll fix:

1. Parameterize socat startup
2. Parameterize socat host IP/Port
3. Create a while true socat sleep script to just loop around socat in case it'd fail

Then we should be basically there...

**Comment by rvleij** [comment] 2021-11-26 23:47
OK, never mind, I couldn't just leave this and sleep haha. If you get the "testing" tag working, then move on to the "dev" tag.
Use the following Docker startup extra's:

-e "SOCAT_ENABLE=TRUE" -e "SOCAT_HOST=192.168.100.15" -e "SOCAT_PORT=1111"

without those, nothing will run (like normal), with those socat will be started in a loop handled by /usr/local/bin/socat_loop.py.

I think we're good then, please test then I'll just put this in the normal "release" and document it on Docker Hub.

**Comment by mvank** [comment] 2021-11-28 15:23
I notices when starting to use the testing version that my ser2net service is stopping:
_`ser2net[32082]: read error for port ipv4,tcp,5000: Connection reset by peer.`_
This was running stable since few week till I started using the testing version.

After restarting ser2net service, all is working fine...

**Comment by rvleij** [comment] 2021-11-29 07:41
Hmm, that's weird. Socat is started like this:

socat pty,link=/dev/ttyUSB4,raw,user=p1mon,group=dialout,mode=777 tcp:<IP>:<PORT>,forever,interval=10

Is that how you would start it manually as well? Maybe the ser2net also has a "forever" to not just sit there and wait?

Or another option is I remove the "host" and "post" and just give you a "socat cmd line" to specify everything yourself.

You can test different options by doing docker -it exec container_name bash and then killing / starting socat.

**Comment by Dinges28** [comment] 2021-12-08 18:56
The Testing and the dev work like a charm although the logfile is flooded with the following error:

`2021/12/08 19:55:55 socat[19427] E exactly 2 addresses required (there are 4); use option "-h" for help
2021/12/08 19:55:55 socat[19429] E exactly 2 addresses required (there are 4); use option "-h" for help
2021/12/08 19:55:55 socat[19431] E exactly 2 addresses required (there are 4); use option "-h" for help
2021/12/08 19:55:55 socat[19433] E exactly 2 addresses required (there are 4); use option "-h" for help
`

**Comment by Dinges28** [comment] 2021-12-08 19:06
> The Testing and the dev work like a charm although the logfile is flooded with the following error:
> 
> `2021/12/08 19:55:55 socat[19427] E exactly 2 addresses required (there are 4); use option "-h" for help 2021/12/08 19:55:55 socat[19429] E exactly 2 addresses required (there are 4); use option "-h" for help 2021/12/08 19:55:55 socat[19431] E exactly 2 addresses required (there are 4); use option "-h" for help 2021/12/08 19:55:55 socat[19433] E exactly 2 addresses required (there are 4); use option "-h" for help `

That was caused by wrong quotation marks ... 


But I do see 1 other error coming by that causes the container to get an unhealthy status:
```
smbd: unrecognized service
Traceback (most recent call last):
  File "/p1mon/scripts/P1Watchdog.py", line 1323, in <module>
    MainProg()
  File "/p1mon/scripts/P1Watchdog.py", line 127, in MainProg
    getCpuTemperature()
  File "/p1mon/scripts/P1Watchdog.py", line 1067, in getCpuTemperature
    tfile = open('/sys/class/thermal/thermal_zone0/temp','r')
```

How to get rid of the unhealthy state?

**Comment by Dinges28** [comment] 2021-12-08 19:31
P1Mon will not connect to /dev/ttyUSB4..
It keeps trying to connect to /dev/ttyUSB0.. how to resolve??

**Comment by rvleij** [comment] 2021-12-08 20:11
Hi, did the unhealthy state due to temp monitoring happen in the old version as well or is this something new? I would have to make some adjustment to that, to hardcode temp and make it look healthy or monitor the container some other way. Will have a look at it.

**Comment by rvleij** [comment] 2021-12-08 20:11
> P1Mon will not connect to /dev/ttyUSB4.. It keeps trying to connect to /dev/ttyUSB0.. how to resolve??

You'd have to change the serial port setting in P1Mon itself. That should be possible in the settings?

**Comment by Dinges28** [comment] 2021-12-08 20:22
I rolled back a version, The unhealthy status stay's, that is not a new one!

![image](https://user-images.githubusercontent.com/39988228/145278737-06afcdd0-6d07-4fd8-ab5f-a374a881535a.png)
I was wondering.. Am I looking wrong? Or is it not possible to change it?

**Comment by rvleij** [comment] 2021-12-08 21:06
Did you change it on the docker command line as well?

**Comment by Dinges28** [comment] 2021-12-08 21:10
This is my docker command:
```
sudo docker run -d -p 81:80 -p 10721:10721 -p 40721:40721 --name="p1mon" \
-h p1mon --cap-add=SYS_NICE \
--tmpfs /tmp --tmpfs /run -v /home/dinges/appdata/p1monitor/ramdisk:/p1mon/mnt/ramdisk:rw \
-v /home/dinges/appdata/p1monitor/data:/p1mon/data:rw -v /home/dinges/appdata/p1monitor/p1mon/usbdisk:/p1mon/mnt/usb:rw \
-v /etc/localtime:/etc/localtime:ro \
-e "SOCAT_ENABLE=TRUE" \
-e "SOCAT_HOST=192.168.10.31" \
-e "SOCAT_PORT=23" \
--restart=unless-stopped \
rvleij/p1monitor:dev
```

**Comment by rvleij** [comment] 2021-12-09 11:12
Good one. How did @mvank actually get this to work? Maybe I should add an parameter on which port to run SOCAT, so that you can choose to run it on the default TTYUSB0 instead of the TTYUSB4 I picked now? Because you can't add that as a device to the docker run options, since it doesn't exist on the host system and you can't seem to change serial port on P1 itself somehow.

**Comment by rvleij** [comment] 2021-12-09 11:13
I don't use SOCAT so I can't really test it, that's why I need your input on how to make this somewhat userfriendly without changing too much in the container itself. I will look at the health status, see what I can do there. I'll open a new issue for that to track it.

**Comment by Dinges28** [comment] 2021-12-09 11:19
> 

A -e for the usbport to select would be the solution.. 

because.. yes, I cannot share the device, because it does not exists when creating the container.

**Comment by mvank** [comment] 2021-12-10 13:20
Hi @rvleij , I used this setting in my socat.conf
`OPTIONS="pty,link=/dev/ttyUSB0,raw,user=p1mon,group=dialout,mode=777 tcp:192.168.1.15:5000"`

**Comment by Dinges28** [comment] 2021-12-10 13:26
I'm using this one
```
sudo /usr/bin/socat -T60 pty,link=/dev/ttyUSB0,rawer,group-late=dialout,mode=660 tcp:192.168.10.31:23.,retry=forever,interval=30
```

**Comment by rvleij** [comment] 2021-12-10 13:34
The solution might actually be super simple: I just change the default socat device to ttyusb0, so that p1monitor picks that up (it's the default I think). THen without socat you need to map a hardware device, and with socat you use eh socat. I'll change it in the testing tag, have to build new images and I will try to do that before the weekend so you can test.

**Comment by mvank** [comment] 2021-12-10 13:37
I created a script for myself, after docker is started i run:
`docker exec ./socat-ttyUSB0.sh p1test`

Compose File
```
version: '3.8'
services:

  p1test:
    hostname: p1test
    container_name: p1test
    image: rvleij/p1monitor
    ports:
      - 8181:80
    volumes:
      - /docker/test/alldata/data:/p1mon/data
      - /docker/test/alldata/usbdisk:/p1mon/mnt/usb
      - /docker/test/alldata/mnt/ramdisk:/p1mon/mnt/ramdisk
      - /etc/localtime:/etc/localtime:ro
      - /docker/test/socat-ttyUSB0.sh:/socat-ttyUSB0.sh
      - /docker/test/socat.conf:/etc/default/socat.conf
    tmpfs:
      - /run
      - /tmp
    cap_add:
      - SYS_NICE
    restart: unless-stopped
```

**socat.conf**
`OPTIONS="pty,link=/dev/ttyUSB0,raw,user=p1mon,group=dialout,mode=777 tcp:192.168.1.15:5000"`

**socat-ttyUSB0.sh**
```
> apt install $serviceName -y
> git clone https://github.com/asaif/socat-init.git &&
> cp socat-init/socat /etc/init.d/ &&
>chmod +x /etc/init.d/socat &&
> service socat restart
```

**Comment by Dinges28** [comment] 2021-12-10 13:39
> 

Give a shout, I'll try the test-image

**Comment by rvleij** [comment] 2021-12-10 16:07
Try the testing tag, there I put socat on ttyusb0, which should work out of the box.

**Comment by mvank** [comment] 2021-12-10 18:30
after adjusting the following file: /usr/local/bin/socat_loop.py

/dev/ttyUSB4 --> /dev/ttyUSB0

It is working

```
import os

enable,host,port=os.environ.get('SOCAT_ENABLE'),os.environ.get('SOCAT_HOST'),os.environ.get('SOCAT_PORT')

import os

while enable:
  os.system("socat pty,link=/dev/ttyUSB4,raw,user=p1mon,group=dialout,mode=777 tcp:%s:%s,forever,interval=10" %(host,port))
```

**Comment by rvleij** [comment] 2021-12-10 20:37
But that’s what I changed in the testing tag. So if you run that one you can verify it’s allright and then I push it to the latest tag after the weekend.

**Comment by mvank** [comment] 2021-12-10 22:35
latest testing version is working for me

<img width="259" alt="image" src="https://user-images.githubusercontent.com/7591996/145649857-9504db48-9dab-40ff-8244-41298fd04da1.png">

**Comment by rvleij** [comment] 2021-12-13 07:39
OK, then I'll release this as latest / 1.5.0-2 and we should be fine. Thanks for testing!

**Comment by mvank** [comment] 2021-12-13 07:47
Checked this morning, still running stable. Thank you for the effort you have put into it.

**Comment by rvleij** [comment] 2021-12-13 20:24
Pushed to v1.5.0-2 (& latest), so I will close this issue. Please open new issue if I need to change something. Happy that it's working for you guys. :)

**Closed as completed by rvleij** 2021-12-13 20:24 UTC
